<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="5" hostname="DESKTOP-LI9TG70" failures="1" tests="1" name="Default test" time="16.537" errors="0" timestamp="2022-10-02T17:31:16 EDT">
  <testcase classname="com.salesforce.automation.scripts.TestScripts" name="emptyPasswordTC1" time="3.159">
    <failure type="java.lang.AssertionError" message="expected [Please enter your] but found [Please enter your password.]">
      <![CDATA[java.lang.AssertionError: expected [Please enter your] but found [Please enter your password.]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at com.salesforce.automation.scripts.TestScripts.emptyPasswordTC1(TestScripts.java:51)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- emptyPasswordTC1 -->
  <testcase classname="com.salesforce.automation.scripts.TestScripts" name="logoutSuccessTC3" time="0.0">
    <ignored/>
  </testcase> <!-- logoutSuccessTC3 -->
  <testcase classname="com.salesforce.automation.scripts.TestScripts" name="invalidLoginTC4B" time="0.0">
    <ignored/>
  </testcase> <!-- invalidLoginTC4B -->
  <testcase classname="com.salesforce.automation.scripts.TestScripts" name="loginSuccessTC2" time="0.0">
    <ignored/>
  </testcase> <!-- loginSuccessTC2 -->
  <testcase classname="com.salesforce.automation.basetest.BaseAutomation" name="browserSel" time="0.0">
    <ignored/>
  </testcase> <!-- browserSel -->
  <testcase classname="com.salesforce.automation.scripts.TestScripts" name="forgotPasswordTC4A" time="0.0">
    <ignored/>
  </testcase> <!-- forgotPasswordTC4A -->
</testsuite> <!-- Default test -->
