<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-LI9TG70" failures="1" tests="5" name="com.salesforce.automation.scripts.TestScripts" time="70.469" errors="0" timestamp="2022-10-02T22:46:17 EDT" skipped="1">
  <testcase classname="com.salesforce.automation.scripts.TestScripts" name="loginSuccessTC2" time="25.184"/>
  <system-out/>
  <testcase classname="com.salesforce.automation.scripts.TestScripts" name="emptyPasswordTC1" time="15.292">
    <failure message="expected [Please enter your] but found [Please enter your password.]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Please enter your] but found [Please enter your password.]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at com.salesforce.automation.scripts.TestScripts.emptyPasswordTC1(TestScripts.java:49)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- emptyPasswordTC1 -->
  <system-out/>
  <testcase classname="com.salesforce.automation.scripts.TestScripts" name="logoutSuccessTC3" time="6.898">
    <skipped/>
  </testcase> <!-- logoutSuccessTC3 -->
  <system-out/>
  <testcase classname="com.salesforce.automation.scripts.TestScripts" name="forgotPasswordTC4A" time="14.298"/>
  <system-out/>
  <testcase classname="com.salesforce.automation.scripts.TestScripts" name="invalidLoginTC4B" time="8.797"/>
  <system-out/>
</testsuite> <!-- com.salesforce.automation.scripts.TestScripts -->
